fixed broken config file for circleci
dyedurham/GlobalX.Hypermedia.AspNetCore pull request #7
Opened 2019-12-11 00:31 UTC by swetashah18

Fixed broken config
deleted unnecessary file

2019-12-14 03:57 UTC, drewfreyling requested changes

2019-12-14 03:57 UTC, drewfreyling commented on .circleci/config.yml
> +      - run: dotnet restore src/GlobalX.Hypermedia.AspNetCore.sln
From .net core 2 and above you don't need to explicitly run a restore.
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack

2019-12-14 03:57 UTC, drewfreyling commented on .circleci/config.yml
> +      - run: dotnet pack src/GlobalX.Hypermedia.AspNetCore.sln --include-source --include-symbols -o ../../nuget
This should be set to pack in release mode

2020-02-26 05:50 UTC, Evangelinexx commented
What's happening with this one?

2020-03-23 04:59 UTC, merged